baseURL = "https://guides.xivresources.com/"
languageCode = "en-us"
title = "Balance Guides"
theme = "glam"

[params]
  maxLevel = 90
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

[menu]
  [[menu.main]]
    identifier = 'jobs'
    name = 'Combat Jobs'
    url = '/jobs/'
    weight = 10
  [[menu.main]]
    identifier = 'other-jobs'
    name = 'Other Jobs'
    url = '/jobs/'
    weight = 20
  [[menu.main]]
    identifier = 'encounters'
    name = 'Fight Encounters'
    url = '/encounters/'
    weight = 30
  [[menu.main]]
    identifier = 'tools'
    name = 'Tools'
    url = '/tools/'
    weight = 40
  [[menu.main]]
    identifier = 'other-guides'
    name = 'Other Guides'
    url = '/guides/'
    weight = 50
  [[menu.header]]
    identifier = 'news'
    name = 'Newsfeed'
    url = '/news/'
    weight = 60
  [[menu.footer]]
    identifier = 'info'
    name = 'Info'
    weight = 60
