backend:
  name: github
  repo: The-Balance-FFXIV/balance-static
  branch: main
  base_url: https://auth.xivresources.com
  site_domain: guides.xivresources.com
  cms_label_prefix: cms/
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img
site_url: https://guides.xivresources.com
show_preview_links: true
###
# Be careful in editing this; discuss in website channels first!
##
collections:
  ##
  # Job guides - tanks section
  ##
  # Warrior
  - name: 'war-guides'
    label: 'War'
    description: "Warrior Guides"
    folder: 'content/jobs/tanks/warrior'
    create: true
    slug: '{{slug}}'
    preview_path: 'jobs/tanks/warrior/{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
