backend:
  name: github
  repo: The-Balance-FFXIV/balance-static
  branch: main
  base_url: https://auth.xivresources.com
  site_domain: guides.xivresources.com
  cms_label_prefix: cms/
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img
site_url: https://guides.xivresources.com
show_preview_links: true
###
# Be careful in editing this; discuss in website channels first!
##
collections:
  ##
  # Regular guides
  ##
  - name: 'guides'
    label: 'guide'
    description: "General Guides"
    folder: 'content/guide'
    create: true
    slug: '{{slug}}'
    preview_path: 'guide/{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  ##
  # Job guides - tanks section
  ##
  # Warrior
  - name: 'war-guides'
    label: 'war'
    description: "Warrior Guides"
    folder: 'content/jobs/tanks/warrior'
    create: true
    slug: '{{slug}}'
    preview_path: 'jobs/tanks/warrior/{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  ##
  # Job guides - melee section
  ##
  # Dragoon
  - name: 'drg-guides'
    label: 'drg'
    description: "Dragoon Guides"
    folder: 'content/jobs/melee/dragoon'
    create: true
    slug: '{{slug}}'
    preview_path: 'jobs/melee/dragoon/{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  # Reaper
  - name: 'rpr-guides'
    label: 'rpr'
    description: "Reaper Guides"
    folder: 'content/jobs/melee/reaper'
    create: true
    slug: '{{slug}}'
    preview_path: 'jobs/melee/reaper/{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  ##
  # Job guides - ranged section
  ##
  # Machinist
  - name: 'mch-guides'
    label: 'mch'
    description: "Machinist Guides"
    folder: 'content/jobs/ranged/machinist'
    create: true
    slug: '{{slug}}'
    preview_path: 'jobs/ranged/machinist/{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  ##
  # Job guides - caster section
  ##
  # Black Mage
  - name: 'blm-guides'
    label: 'blm'
    description: "Black Mage Guides"
    folder: 'content/jobs/casters/black-mage'
    create: true
    slug: '{{slug}}'
    preview_path: 'jobs/casters/black-mage/{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
